### ISSUE TITLE
What does it mean ? - Results score

### ISSUE THREAD

**Issue by rodmandi** [guillaumegenthial/tf_ner#15]
![seleccion_024](https://user-images.githubusercontent.com/43979543/47813228-0a7d5000-dd10-11e8-813f-bb46b9138e3b.png)

Well as you can see, we have in "Francisco" I-LOC B-LOC What does it mean? What is the meaning of I-LOC and B-LOC? i don't know if the meaning of I-LOC is that tag was the correct tag, and B-LOC was the the predicted tag, or maybe another example Moscow B-LOC B-LOC.

Thank you!

**Comment by guillaumegenthial** [comment]
Hi @rodmandi,

The first tag is the true tag (from the dummy dataset), the second tag is the prediction.
I assume you trained the model just on this dummy dataset, which would result in a crappy model (almost perfectly overfitted on the dummy dataset).

So in Francisco I-LOC B-LOC it means that the model made a mistake by predicting B-LOC instead of I-LOC.

Hope that helps

**Comment by bhushanbrb** [comment]
@rodmandi  Just to add more 
In case you do not know this may help ... B-I-O is Begin Inside Outside Input data pattern.
Explanation from @guillaumegenthial blog 
`In the CoNLL2003 task, the entities are LOC, PER, ORG and MISC for locations, persons, orgnizations and miscellaneous. The no-entity tag is O. Because some entities (like New York) have multiple words, we use a tagging scheme to distinguish between the beginning (tag B-...), or the inside of an entity (tag I-...). Other tagging schemes exist (IOBES, etc). However, if we just pause for a sec and think about it in an abstract manner, we just need a system that assigns a class (a number corresponding to a tag) to each word in a sentence.`
--> **What is the meaning of I-LOC and B-LOC?**
**Word from sequence | TrueTag | PredictedTag**
