### ISSUE TITLE
Provide an example to public NER data set

### ISSUE THREAD

**Issue by shanalikhan** [guillaumegenthial/tf_ner#5]
In readme, there is no example from where i can use https://github.com/davidsbatista/NER-datasets in this tf_ner ? can you provide some an example to use any of data set in your tensorflow model

**Comment by guillaumegenthial** [comment]
Hi @shanalikhan, the CONLL2003 dataset is not public, and I have a few doubts about the legality of making it available to the public like that! That's why I include a fake dataset to help your convert your dataset to the right format.
You can always use the datasets made available in the repo you link to. You just need to write a simple script to convert it to the right format so that you can use with the `tf_ner` source code!
